import Head from "next/head";
import Layout from "@/components/Layout";
import Hero from "@/components/Home/Hero";
import InfoBlock from "@/components/Home/InfoBlock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Home">
        <Hero />
        <InfoBlock />
      </Layout>
    </>
  );
}
